# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import member.models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', member.models.MyUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='phone',
        ),
        migrations.AddField(
            model_name='myuser',
            name='nickname',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(choices=[('f', 'Facebook'), ('n', 'Naver'), ('g', 'General')], default='g', max_length=1),
        ),
    ]
