# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_email_verification',
            field=models.BooleanField(default=True),
        ),
    ]
