# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 09:38
from __future__ import unicode_literals

from django.db import migrations
import utils.customfield.custom_imagefield


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20171110_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_2',
            field=utils.customfield.custom_imagefield.CustomImageField(blank=True, default=None, upload_to='post/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_3',
            field=utils.customfield.custom_imagefield.CustomImageField(blank=True, default=None, upload_to='post/%Y/%m/%d'),
        ),
    ]
