# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20171030_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_2',
            field=models.ImageField(blank=True, default=None, upload_to='post/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_3',
            field=models.ImageField(blank=True, default=None, upload_to='post/%Y/%m/%d'),
        ),
    ]
