# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20171114_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sell_or_buy',
            field=models.CharField(choices=[('s', 'Sell'), ('b', 'Buy')], max_length=4),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=130),
        ),
    ]
