# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
