# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20171127_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='visible',
        ),
        migrations.AddField(
            model_name='message',
            name='recipient_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_delete',
            field=models.BooleanField(default=False),
        ),
    ]
